name: 三合一全自动歌曲爬虫
on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    # 强制启用 Node.js 24 运行，解决弃用警告
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install requests beautifulsoup4
      - run: python main.py
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 自动更新三合一歌曲资源
